# Generated by Django 5.1.4 on 2024-12-27 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('IP', 'In Progress'), ('DF', 'Delivered')], default='PD', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifiyed', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
